const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const creator = fs.readFileSync(path.join(root, 'script/pages/floorplan.js'), 'utf8');
const dashboard = fs.readFileSync(path.join(root, 'script/pages/myfloorplans.js'), 'utf8');
const dashboardPage = fs.readFileSync(path.join(root, 'pages/myfloorplans.html'), 'utf8');
const creatorCss = fs.readFileSync(path.join(root, 'css/floorplan.css'), 'utf8');
const creatorPage = fs.readFileSync(path.join(root, 'pages/tool-floorplan.html'), 'utf8');
const cloud = fs.readFileSync(path.join(root, 'script/modules/floorplans-cloud.js'), 'utf8');

assert.match(creator, /assets\.getHomes\(\)/);
assert.doesNotMatch(creator, /assets\.getVehicles\(\)/);
assert.doesNotMatch(creator, /fp-asset-optgroup">Vehicles/);
assert.match(creator, /data-value="Other"/);
assert.match(creator, /planAsset = currentPlanAsset\(\) \|\| 'Other'/);
assert.match(creator, /const asset = currentModalAsset\(\) \|\| 'Other'/);
assert.doesNotMatch(creator, /Please select an asset for the floor plan/);
assert.match(dashboard, /assets\.push\(\{ label: 'Other'/);
assert.match(dashboard, /\(p\.asset \|\| 'Other'\) === asset\.label/);
assert.match(creator, /location\.href = 'myfloorplans\.html'/);
assert.match(dashboardPage, /window\.location\.href='mytools 2\.html'/);
assert.doesNotMatch(dashboardPage, /onclick="history\.back\(\)"/);
assert.match(creator, /new ResizeObserver\(resizeCanvas\)/);
assert.match(creator, /canvas\.getPointer\(opt\.e, true\)/);
assert.match(creator, /canvas\.zoomToPoint\(new fabric\.Point\(pointer\.x, pointer\.y\), newZ\)/);
assert.match(creator, /Math\.pow\(0\.9975, opt\.e\.deltaY\)/);
assert.match(creator, /const GRID_TARGET_PX = 48;/);
assert.match(creator, /const thinW = 0\.75 \/ zoom;/);
assert.equal((creator.match(/isMajor \? '#aaa' : '#c8c8c8'/g) || []).length, 2);
assert.match(creator, /const labelX = axisVisible \? -4 \/ zoom : axisIsLeft \? bx1 \+ 8 \/ zoom : bx2 - 8 \/ zoom;/);
assert.match(creator, /const labelY = Math\.max\(by1 \+ 18 \/ zoom, Math\.min\(-4 \/ zoom, by2 - 6 \/ zoom\)\);/);
assert.match(creator, /const pointer = canvas\.getPointer\(e, true\)/);
assert.match(creatorCss, /\.fp-tool-label\s*{[^}]*font-size: 0\.8rem/s);
assert.match(creatorPage, /id="newPlanFloorDropdown"/);
assert.match(creatorPage, /id="newPlanFloorInput"/);
assert.match(creatorPage, /id="planFloorDropdown"/);
assert.match(creatorPage, /id="planFloorInput"/);
assert.match(creatorPage, /id="newPlanFloorOtherRow" hidden/);
assert.match(creatorPage, /id="planFloorOtherRow" hidden/);
assert.match(creator, /function floorNamesForAsset\(assetLabel\)/);
assert.match(creator, /function ordinalFloor\(number\)/);
assert.match(creator, /return \(hasBasement \? \['Basement'\] : \[\]\)/);
assert.match(creator, /Array\.from\(numbered\)\.sort\(\(a, b\) => a - b\)\.map\(ordinalFloor\)/);
assert.match(creator, /assets\.updateHome\(home\.id, \{ floorNames \}\)/);
assert.match(creator, /Please select or add a floor\./);
assert.match(creator, /data-value="__other__">Other/);
assert.match(creator, /function setFloorInputVisible\(target, visible\)/);
assert.equal((creator.match(/value\.textContent = 'Other'/g) || []).length, 2);
assert.match(creator, /savePlanData\(name, data, preview, planAsset, planFloor\)/);
assert.match(cloud, /data\._floorplanFloor = plan\.floor/);
assert.match(cloud, /floor: row\.data && row\.data\._floorplanFloor/);
assert.match(dashboard, /class="fp-grid-floor"/);

console.log('Floor plan asset checks passed.');
