const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

function read(file) {
    return fs.readFileSync(path.join(__dirname, '..', file), 'utf8');
}

const migration = read('supabase/migrations/20260920180636_fix_floorplans_neighborhood_documents_photos.sql');
const assets = read('script/pages/asset-boxes.js');
const homesCss = read('css/homes.css');
const gallery = read('script/pages/gallery.js');
const documents = read('script/pages/mydocuments.js');
const documentsCss = read('css/documents.css');
const neighborhood = read('script/pages/myneighborhood.js');
const neighborhoodPage = read('pages/myneighborhood.html');
assert.match(neighborhoodPage, /id="nb-rules-box"/);
assert.match(neighborhoodPage, /id="nb-add-rule"/);
assert.match(neighborhoodPage, /id="nb-send-alert"/);
assert.match(neighborhoodPage, /id="nb-rule-popup"/);
assert.match(neighborhoodPage, /id="nb-alert-popup"/);
assert.match(neighborhood, /familyRequest\('neighborhood-alert'/);
const homesPage = read('pages/myhomes.html');
const documentsPage = read('pages/mydocuments.html');
const projectPage = read('pages/myproject.html');
const projectScript = read('script/pages/myproject.js');
const projectsCloud = read('script/modules/projects-cloud.js');
const vehiclesPage = read('pages/myvehicles.html');
const profilePage = read('pages/myprofile.html');
const dashboardPage = read('pages/dashboard.html');
const vehicleRegister = read('script/modules/vehicle-register.js');
const projectPhotoMigration = read('supabase/migrations/20260923220541_project_photo_library.sql');
const planningCss = read('css/planning.css');
const floorplanCss = read('css/floorplan.css');
const floorplanScript = read('script/pages/floorplan.js');
const floorplansScript = read('script/pages/myfloorplans.js');
const floorplanPage = read('pages/tool-floorplan.html');

for (const table of ['projects', 'floorplans', 'asset_photos']) {
    assert.match(migration, new RegExp(`grant select, insert, update, delete on public\\.${table} to authenticated, service_role`));
}
assert.match(migration, /add column if not exists neighborhood_id uuid references public\.neighborhoods/);
assert.match(migration, /public\.is_current_neighborhood_member\(neighborhood_id\)/);
assert.match(migration, /public\.is_current_neighborhood_editor\(neighborhood_id\)/);
assert.match(migration, /coalesce\(extracted_data->>'privacy', 'neighborhood'\) = 'neighborhood'/);
assert.match(assets, /new CustomEvent\('asset:selected'/);
assert.match(assets, /url\.searchParams\.set\('id', id\)/);
assert.match(assets, /const editBtn = el\.querySelector\('\.doc-edit-btn'\)/);
assert.doesNotMatch(assets, /el\.appendChild\(editBtn\)/);
assert.match(assets, /function renderProjects\(\)/);
assert.match(assets, /renderProjectFolders\(asset, docs, renderProjects\)/);
assert.match(documents, /renderProjectFolders: renderProjectFolders/);
assert.match(documentsCss, /#doc-add-popup \.popup-content\s*{[^}]*max-width: 640px/s);
assert.match(documentsCss, /#doc-search\s*{[^}]*background-color: var\(--bg-primary\)/s);
assert.match(documentsCss, /\.doc-project-add:hover\s*{[^}]*box-shadow: none/s);
assert.match(documentsCss, /\.doc-projects\s*{[^}]*display: flex/s);
assert.match(documentsCss, /@media \(max-width: 760px\)\s*{\s*\.doc-project-folder \{ flex-basis: calc\(\(100% - 28px\) \/ 3\); \}/s);
assert.match(documentsCss, /#project-doc-list \.doc-row-left/);
assert.match(documentsCss, /@media \(max-width: 850px\)\s*{\s*#project-doc-list \.doc-cell-uploaded/s);
assert.match(documentsCss, /@media \(max-width: 475px\)\s*{\s*#project-doc-list \.doc-cell-asset/s);
assert.match(documents, /function documentOnlyAssets\(\)/);
assert.match(documents, /addGroup\('Neighborhood', neighborhoods\)/);
assert.match(documents, /<li class="asset-optgroup">Other<\/li>/);
assert.match(documents, /data-value="__other__">Other<\/button>/);
assert.match(documents, /rec\.neighborhoodId = selectedAssetKind === 'neighborhood'/);
assert.match(documents, /concat\(Object\.keys\(loadProjects\(\)\)\)/);
assert.match(documents, /if \(list\.indexOf\(name\) === -1\) list\.push\(name\)/);
assert.match(documents, /const projectSet = new Set\(projects\)/);
assert.doesNotMatch(documents, /list\.unshift\(name\)/);
assert.match(projectsCloud, /query: \{ select: 'asset,name', order: 'created_at\.asc' \}/);
assert.match(documents, /window\.addEventListener\('assets:changed', function \(\) \{\s*refreshDocumentAssetMenu\(\);\s*updateView\(\)/);
assert.match(documents, /registeredAssets\(\)\.forEach\(function \(asset\) \{ byAsset\.set\(asset\.label, \[\]\); \}\)/);
assert.match(documents, /neighborhoodAssetEntries\(\)\.forEach\(function \(asset\) \{ byAsset\.set\(asset\.label, \[\]\); \}\)/);
assert.match(documents, /documentOnlyAssets\(\)\.forEach\(function \(asset\) \{ byAsset\.set\(asset, \[\]\); \}\)/);
assert.match(documents, /if \(sortedArr\.length\) content\.appendChild\(renderHeaderRow\(\)\)/);
assert.doesNotMatch(documents, /if \(!items\.length\) \{\s*const groupsEl/);
assert.match(documents, /if \(aRegistered === -1\) return 1/);
assert.match(documents, /searchScore: searchScore/);
assert.match(documents, /key: 'format', text: normalizeForSearch\(it\.format \|\| info\.label\)/);
assert.match(projectScript, /MyMaintenanceDocs\.searchScore\(d, q\)/);
assert.match(projectPage, /<label>File format<\/label>\s*<input type="text" id="doc-format" readonly>/);
for (const page of [vehiclesPage, profilePage, dashboardPage]) {
    for (const type of ['Truck', 'Trailer', 'Scooter', 'Bike']) {
        assert.match(page, new RegExp(`data-value="${type}"`));
    }
    assert.match(page, /id="rv-registration-country"/);
    assert.match(page, /class="asset-dropdown registration-country-dropdown"/);
    assert.doesNotMatch(page, /<select id="rv-registration-country"/);
    assert.match(page, /id="rv-registration-format"/);
}
assert.match(vehicleRegister, /Boat: \{ name: 'e\.g\. My Boat', registration: 'e\.g\. NOR-123', make: 'e\.g\. Bayliner', model: 'e\.g\. VR5'/);
assert.match(vehicleRegister, /vehicleType !== 'Boat' && vehicleType !== 'Bike'/);
assert.match(assets, /\['Car', 'Truck', 'Trailer', 'Scooter', 'Bike', 'Boat', 'Other'\]/);
assert.match(vehicleRegister, /const PLATE_COUNTRIES =/);
assert.match(vehicleRegister, /registrationCountry: country/);
assert.match(vehicleRegister, /plateValid\(country, registration, vehicleType\)/);
assert.match(vehicleRegister, /function flagSvg\(country\)/);
assert.match(vehicleRegister, /registrationCountryMenu\.innerHTML = Object\.keys\(PLATE_COUNTRIES\)/);
assert.match(planningCss, /\.registration-country-dropdown \.asset-toggle \.vehicle-country-flag svg\s*{[^}]*margin-left: 0/s);
assert.match(planningCss, /\.registration-country-dropdown \.asset-menu button\s*{[^}]*padding-left: 10px/s);
assert.match(assets, /prop: 'registrationCountry', defaultValue: 'NO'/);
const plateContext = { window: {}, document: { readyState: 'loading', addEventListener() {} } };
vm.runInNewContext(vehicleRegister, plateContext);
const plates = plateContext.window.MyMaintenanceVehiclePlates;
assert.equal(plates.isValid('NO', 'AB 12345', 'Car'), true);
assert.equal(plates.isValid('NO', '12345', 'Car'), false);
assert.equal(plates.isValid('SE', 'ABC 12D', 'Car'), true);
assert.equal(plates.isValid('DK', 'AB 12 345', 'Trailer'), true);
assert.equal(plates.isValid('DE', 'B AB 1234E', 'Car'), true);
assert.equal(plates.isValid('GB', 'AB12 CDE', 'Car'), true);
assert.equal(plates.isValid('NO', 'NOR-123', 'Boat'), true);
assert.match(homesPage, /id="asset-projects-list"/);
assert.match(homesCss, /\.projects-box\s*{[^}]*grid-column: span 18/s);
assert.match(homesCss, /\.docs-box \.doc-row\s*{[^}]*display: grid[^}]*grid-template-columns/s);
assert.match(homesCss, /\.docs-box \.doc-cell-performed,[\s\S]*?display: none/);
assert.match(homesCss, /\.asset-info-val\s*{[^}]*min-height: 42px/s);
assert.match(homesCss, /\.asset-info-input\s*{[^}]*height: 42px[^}]*border: 2px solid var\(--accent-primary\)[^}]*border-radius: 25px/s);
assert.match(homesCss, /\.asset-info-dropdown \.asset-toggle\s*{[^}]*height: 42px[^}]*border: 2px solid var\(--accent-primary\)[^}]*border-radius: 25px/s);
assert.match(gallery, /window\.GALLERY_ASSET_ID \|\| pageParams\.get\('id'\)/);
assert.match(gallery, /window\.GALLERY_ASSET_TYPE/);
assert.match(gallery, /window\.addEventListener\('asset:selected'/);
assert.match(floorplansScript, /class="doc-project-folder doc-project-add fp-grid-add"/);
assert.match(floorplansScript, /tool-floorplan\.html\?new=1&asset=/);
assert.match(floorplansScript, /tool-floorplan\.html\?new=1'/);
assert.doesNotMatch(floorplansScript, /class="view-button fp-group-create"/);
assert.match(floorplanScript, /pageParams\.get\('new'\) === '1' \? openNewPlanModal\(\) : showFileManager\(\)/);
assert.match(floorplanScript, /currentPlanAsset\(\) \|\| 'Select asset'/);
assert.match(floorplanScript, /currentModalAsset\(\) \|\| 'Other'/);
assert.doesNotMatch(floorplanScript, /Please select an asset for the floor plan\./);
assert.match(floorplanPage, /id="newPlanAssetValue">Select asset<\/span>/);
assert.match(floorplanCss, /\.fp-grid-empty-assets \.fp-grid-add\s*{[^}]*grid-column: 1 \/ -1/s);
assert.match(floorplanCss, /\.fp-grid-card:hover\s*{[^}]*box-shadow: none/s);
assert.match(projectPhotoMigration, /'home', 'vehicle', 'project'/);
assert.match(projectPage, /class="project-summary-layout"/);
assert.match(projectPage, /<h3>Project photos<\/h3>/);
assert.match(projectPage, /window\.GALLERY_ASSET_TYPE = 'project'/);
assert.match(projectScript, /MyMaintenanceProjects\.find\(asset, project\)/);
assert.match(documentsCss, /\.project-overview-row\s*{[^}]*grid-template-rows: minmax\(110px, 0\.7fr\) minmax\(220px, 1\.3fr\)/s);
assert.match(documentsCss, /\.project-cost-cell\s*{[^}]*justify-content: flex-start/s);
assert.match(documentsCss, /\.project-cost-row\s*{[^}]*font-size: 1rem/s);
assert.match(documentsCss, /\.project-summary-layout > \.project-photo-box\s*{[^}]*grid-column: 1;[^}]*grid-row: 1 \/ span 2/s);
assert.match(documentsCss, /\.project-summary-layout > \.project-right-column\s*{[^}]*grid-column: 2;[^}]*grid-row: 1 \/ span 2/s);
assert.match(projectPage, /class="project-right-column"/);
assert.match(projectPage, /class="project-documents-title">Documents<\/h2>/);
assert.match(documentsCss, /\.project-documents-header\s*{[^}]*justify-content: space-between/s);
assert.match(documentsCss, /\.project-right-column #project-overview\s*{[^}]*height: 100%/s);
assert.match(documentsCss, /\.project-summary-layout \.project-photo-box \.photo-box-side\s*{[^}]*grid-template-columns: 1fr/s);
for (const page of [documentsPage, projectPage]) {
    assert.match(page, /id="doc-subproject-dropdown"/);
    assert.match(page, /data-value="Electrician"/);
    assert.match(page, /data-value="Plumber"/);
}
assert.match(documents, /rec\.subproject = selectedSubproject === '__other__'/);
assert.match(projectScript, /class=\"project-cost-summary\"/);
assert.match(projectScript, /d\.subproject \|\| 'General'/);
assert.match(documents, /neighborhood_id: item\.neighborhoodId \|\| null/);
assert.match(documents, /neighborhoodId: row\.neighborhood_id \|\| ''/);
assert.match(neighborhood, /await persistNeighborhoodDocument\(doc\)/);
assert.match(neighborhood, /neighborhoodId: nb\.id/);
assert.match(neighborhood, /del\.className = 'photo-remove'/);
assert.match(neighborhood, /txt\.className = 'ap-photo-text'/);
assert.match(neighborhood, /text: pending\.text \|\| ''/);
assert.doesNotMatch(neighborhoodPage, /id="nbp-photo-options"/);
assert.match(neighborhoodPage, /<label>Pictures<\/label>/);

console.log('PASS: Supabase assets, neighborhood documents, and matching photo upload controls are wired.');
